---
title: "Figure 1: Summary of public health responses"
author: "Hugo Gruson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
---

```{r}
library(dplyr)
library(ggplot2)

library(NpiEurope)
```

```{r}
library(asymptor)

load_epi_data() %>%
  transmute(
    date = as.Date(Date), 
    new_cases = NewCases, 
    new_deaths = NewDeaths,
    country = Country
  ) %>%
  group_by(country) %>%
  mutate(new_cases = pmax(new_cases, 0),
         new_deaths = pmax(new_deaths, 0)) %>%
  mutate(new_cases = slider::slide_dbl(new_cases, mean, .before = 3, .after = 3),
         new_deaths = slider::slide_dbl(new_deaths, mean, .before = 3, .after = 3)) %>%
  summarise(estimate_asympto(cur_data()),
            detected = new_cases) %>%
  ggplot(aes(x = date)) +
    geom_ribbon(aes(ymin = detected + lower, ymax = detected + upper)) +
    geom_line(aes(y = detected), color = "red") +
    facet_wrap(~ country, scales = "free_y")
```


```{r}
for (i in 1:length(countryVec)) {
  country <- countryVec[i]
  print(country)
  country_data <- load_country_data(country)
  country_data$NewCases[which(country_data$NewCases < 0)] <- -country_data$NewCases[which(country_data$NewCases < 0)]
  epi_data <- country_data[, c("Date", "NewCases", "NewDeaths")]
  npi_data <- country_data[, !colnames(country_data) %in% c("NewCases", "NewDeaths", "Country", "Population")]
  epi_data <- estimate_asympto(epi_data, smooth = 7)
  contact_data <- NpiEurope::load_contact_data(country)
  age_data <- load_age_data(country)

  plot_asympto(epi_data)
  ggsave(sprintf("%s/Report_%s.pdf", folder, country))
  temp <- summarise_estimation(sprintf("%s/%s.csv", folder, country), npi_data, contact_data, age_data)
  write.csv(temp, sprintf("%s/estim_%s.csv", folder, country))

}
```

# Reproducibility information

File created on `r Sys.Date()` with the following session details:

<details>
<summary>Session info</summary>

```{r}
sessionInfo()
```

</details>

