---
title: "Figure 2: Model fit of COVID-19 incidence across European countries."
output: rmarkdown::html_document
params:
  export_figs: false
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  class.warning = "collapsable-warnings",
  message = FALSE
)
if (params$export_figs) {
  ncols = 5
} else {
  ncols = 3
}
```

```{r}
library(dplyr)
library(ggplot2)
library(purrr)
```

Despite large variability in terms of public health responses and sociocultural backgrounds across Europe, we were able to accurately quantify viral transmission rates over time in each country before and after implementation of public health responses, reproducing the observed national epidemiological dynamics.

```{r}
library(NpiEurope)
npi_europe <- load_npi_data()
epi_europe <- load_epi_data()
```

```{r}
simulate_from_MCMC <- function(file, npi_europe, epi_europe) {
  
  country <- gsub(".*/((\\w|\\s)+)\\.csv$", "\\1", file)
  
  npi_country <- npi_europe %>%
    filter(Country == country) %>%
    select(-Country)
  
  epi_country <- epi_europe %>%
    filter(Country == country) %>%
    select(-Country) %>%
    mutate(NewCases = pmax(NewCases, 0),
           NewDeaths = pmax(NewDeaths, 0)) %>%
    mutate(lower = asymptor::estimate_asympto(Date, NewCases, NewDeaths, bounds = "lower")$lower) %>%
    mutate(PropAsympto = lower / (lower+NewCases)) %>%
    mutate(PropAsympto = ifelse(is.finite(PropAsympto), PropAsympto, 0)) %>%
    mutate(PropAsympto = slider::slide_dbl(PropAsympto, mean, .before = 3, .after = 3, .complete = FALSE))

  contact_country <- load_contact_data(country)
  age_country <- sirage::load_age_data(country)

  sims <- sirage::simulate_trajectory(
    file,
    epi_country, npi_country, contact_country, age_country,
    Npost = 20
  )
  
  sims <- as.data.frame(do.call(rbind, sims))
  sims$Date <- as.Date(intersect(npi_country$Date, epi_country$Date), origin = "1970-01-01")
  sims$Country <- country
  
  sims <- merge(sims, epi_country)
  
  return(sims)
  
}
```

```{r, fig.height=15, fig.cap='Each panel shows model predictions (black shaded area) and confirmed number of new COVID-19 cases over time for each country.'}
(comparison_simulations <- list.files("../MCMC_NpiEurope", pattern = "\\.csv$", full.names = TRUE) %>%
  map_dfr(simulate_from_MCMC, npi_europe, epi_europe) %>%
  group_by(Country) %>%
#  mutate(crps = crps_sample(NewCases, as.matrix()))
  rowwise() %>%
  mutate(sims_low = quantile(c_across(V1:V20), probs = 0.05),
         sims_high = quantile(c_across(V1:V20), probs = 0.95)) %>%
  ggplot(aes(x = Date)) +
    geom_ribbon(aes(ymin = sims_low, ymax = sims_high)) +
    geom_line(aes(y = NewCases), col = "red") +
    facet_wrap(~ Country, scales = "free_y", ncol = ncols))
```

```{r, eval = FALSE}
ggsave("Figure 2.pdf", width = 29.7, height = 21, units = "cm")
```

```{r, child='_sessionInfo.Rmd'}
```

```{js, echo=FALSE}
(function() {
  var codes = document.querySelectorAll('.collapsable-warnings');
  var code, i, d, s, p;
  for (i = 0; i < codes.length; i++) {
    code = codes[i];
    p = code.parentNode;
    d = document.createElement('details');
    s = document.createElement('summary');
    s.innerText = 'Warnings';
    // <details><summary>Details</summary></details>
    d.appendChild(s);
    // move the code into <details>
    p.replaceChild(d, code);
    d.appendChild(code);
  }
})();
```
