---
title: "Figure 4: Efficiency changes after addition of a new strategy"
author: "Hugo Gruson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
---

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(lme4)
  library(ggplot2)
})
```

```{r}
efficiency_matrix <- NpiEurope::create_summary_matrix("../MCMC_NpiEurope")
```

```{r}
efficiency_matrix %>%
  group_by(Country) %>%
  mutate(dif.efficiency = Efficiency - lag(Efficiency, default = 0)) %>%
  select(-DayStart, -DayEnd, -Efficiency) %>%
  pivot_longer(!c(Country, dif.efficiency, NbStrategies, duration), names_to = "NPI") %>%
  group_by(NPI) %>%
  # Univariate model
  summarise(
#    coeff = coefficients(summary(lmer(dif.efficiency ~ NbStrategies + GDP + duration + value + (1 | Country), data = cur_data())))[5, c(1, 2)],
    coeff = coefficients(summary(lmer(dif.efficiency ~ value + (1 | Country), data = cur_data())))[2, c(1, 2)],
    type = c("est", "sd")
  ) %>%
  pivot_wider(names_from = type, values_from = coeff) %>%
  mutate(diff.effect.control = est,
         low.ci.control = est - 1.96 * sd,
         up.ci.control = est + 1.96 * sd,
         .keep = "unused") %>%
  mutate(Partial = ifelse(grepl("Partial$", NPI), "Partial", "Complete"),
         NPI = gsub("Partial$", "", NPI)) %>%
  ggplot(aes(x = diff.effect.control, y = NPI)) +
  geom_vline(xintercept = 0, color = "darkred", size = 1, linetype = "dashed") +
  geom_errorbarh(aes(xmin = low.ci.control, xmax = up.ci.control)) +
  geom_point() +
  facet_wrap(~ Partial) +
  labs(x = "Change in efficiency when adding each NPI", y = "")
```

# Reproducibility information

File created on `r Sys.Date()` with the following session details:

<details>
<summary>Session info</summary>

```{r}
sessionInfo()
```

</details>
