---
title: "Figure 1: Summary of public health responses"
author: "Hugo Gruson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
---

```{r}
library(NpiEurope)

library(dplyr)
library(purrr)
library(tibble)
library(ggplot2)
```

```{r}
npi_europe <- load_npi_data() %>%
  select(-Date)
```

# Subfig A

```{r}
(
duration_plot <- npi_europe %>%
  group_by(Country) %>%
  summarise(across(everything(), sum)) %>%
  select(-Country) %>%
  map_dfc(function(x) c(median(x[x != 0]), sum(x != 0))) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("NPI") %>%
  rename(Duration = V1,
         Implemented = V2) %>%
  mutate(Implemented = Implemented / 32 * 100) %>%
  ggplot(aes(x = Implemented, y = NPI, fill = Duration)) +
    geom_bar(stat = "identity") +
    theme_bw() +
    labs(x = "% Countries Implemented",
         y = "",
         fill = "Median duration (days)")
)
```


# Subfig B

```{r}
library(ggcorrplot)
(
correlation_plot <- npi_europe %>%
  select(-Country) %>%
  relocate(sort(tidyselect::peek_vars())) %>%
  cor() %>%
  ggcorrplot(method = "circle", type = "upper",
             hc.order = FALSE,
             colors = c("tomato2", "white", "springgreen3"),
             ggtheme = theme_bw,
             legend.title = "Correlation")
)
```

# Collage

```{r}
library(patchwork)

duration_plot + correlation_plot +
  plot_annotation(tag_levels = "A") &
  theme(legend.position = "top")
```

```{r echo = FALSE, eval = FALSE}
ggsave("Figure 1.pdf", width = 29.7, height = 21, units = "cm")
```

# Reproducibility information

File created on `r Sys.Date()` with the following session details:

<details>
<summary>Session info</summary>

```{r}
sessionInfo()
```

</details>
