---
title: "Figure 3: Efficiency of different NPIs"
author: "Hugo Gruson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
---

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(tidyr)
  library(tibble)
})
```

```{r}
efficency_matrix <- NpiEurope::create_summary_matrix("../MCMC_NpiEurope")
```

# Subfig A

```{r}
(
hist_plot <- ggplot(efficency_matrix, aes(y = Efficiency)) +
  geom_histogram(binwidth = 0.05, fill = "#69b3a2", color = "#e9ecef", alpha = 0.9) +
  geom_hline(yintercept = 0.66, color = "darkred", lty = "dashed", size = 2) +
  labs(x = "Public Health Responses")
)
```

```{r}
(
number_efficiency_plot <- ggplot(efficency_matrix, aes(x = NbStrategies, y = Efficiency)) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = 0.66, color = "darkred", lty = "dashed", size = 2) +
  labs(x = "NPIs implemented") +
  scale_x_continuous(breaks = seq(1, 13, 2))
)
```

# Subfig B

```{r}
(
efficiency_uni_plot <- efficency_matrix %>%
  select(-DayStart, -DayEnd, -Country, -duration) %>%
  pivot_longer(!c(Efficiency, NbStrategies), names_to = "NPI") %>%
  group_by(NbStrategies, NPI) %>%
  summarise(coeff = coefficients(lm(Efficiency ~ value, data = cur_data()))[2]) %>%
  filter(NbStrategies >= 4 & NbStrategies <= 11) %>%
  ggplot(aes(x = NbStrategies, y = NPI, fill = coeff)) +
    geom_tile() +
    geom_text(aes(label = round(coeff, 2)), size = 2.5) +
    scale_fill_gradient2(high = "darkgreen") +
    scale_x_continuous(breaks = seq(1, 11)) +
    labs(x = "NPIs implemented", y = "")
)
```

# Subfig C: NPI in the highest efficiency responses

````{r}
(
max_efficiency_plot <- efficency_matrix %>%
  arrange(NbStrategies) %>%
  group_by(NbStrategies) %>%
  filter(Efficiency == max(Efficiency)) %>%
  ungroup() %>%
  select(!any_of(c("Efficiency", "DayStart", "DayEnd", "GDP", "Country", "NbStrategies", "duration"))) %>%
  t() %>%
  as.data.frame() %>%
  setNames(seq_len(ncol(.))) %>%
  rownames_to_column("NPI") %>%
  pivot_longer(-NPI, names_to = "NbStrategies") %>%
  mutate(NbStrategies = as.integer(NbStrategies)) %>%
  filter(NbStrategies >= 4 & NbStrategies <= 11) %>%
  ggplot(aes(x = NbStrategies, y = NPI, fill = value)) +
    geom_tile() +
    scale_x_continuous(breaks = seq(1, 11)) +
    labs(x = "NPIs implemented", y = "") +
    theme(legend.position = "none")
)
```

# Collage and export as pdf

```{r, eval = FALSE}
library(patchwork)

((hist_plot / number_efficiency_plot) | efficiency_uni_plot | max_efficiency_plot) &
  (theme_bw() + theme(legend.position = "none"))
ggsave("Figure 3.pdf", width = 29.7, height = 21, units = "cm")
```

# Reproducibility information

File created on `r Sys.Date()` with the following session details:

<details>
<summary>Session info</summary>

```{r}
sessionInfo()
```

</details>
