---
title: "ESM: report rate and efficiencies for each country"
author: "Hugo Gruson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
---

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
})
```

```{r}
library(NpiEurope)
epi_europe <- load_epi_data()
npi_europe <- load_npi_data()
```

```{r}
library(asymptor)

epi_europe %>%
  transmute(
    date = as.Date(Date), 
    new_cases = NewCases, 
    new_deaths = NewDeaths,
    country = Country
  ) %>%
  group_by(country) %>%
  mutate(new_cases = pmax(new_cases, 0),
         new_deaths = pmax(new_deaths, 0)) %>%
  mutate(new_cases = slider::slide_dbl(new_cases, mean, .before = 3, .after = 3),
         new_deaths = slider::slide_dbl(new_deaths, mean, .before = 3, .after = 3)) %>%
  summarise(estimate_asympto(cur_data()),
            detected = new_cases) %>%
  ggplot(aes(x = date)) +
    geom_ribbon(aes(ymin = detected + lower, ymax = detected + upper)) +
    geom_line(aes(y = detected), color = "red") +
    facet_wrap(~ country, scales = "free_y")
```


```{r, results='asis'}
list.files("../MCMC_NpiEurope/", "\\.csv$", full.names = TRUE) %>%
  lapply(function(f) {
      country <- gsub(".*/((\\w|\\s)+)\\.csv$", "\\1", f)

      npi_country <- npi_europe %>%
        filter(Country == country) %>%
        select(-Country)
    
      contact_country <- load_contact_data(country)
      age_country <- sirage::load_age_data(country)
    
      res <- sirage::summarise_estimation(f, npi_country, contact_country, age_country)
      
      cat("### ", country, "\n\n")
      print(knitr::kable(res))
  })
```

# Reproducibility information

File created on `r Sys.Date()` with the following session details:

<details>
<summary>Session info</summary>

```{r}
sessionInfo()
```

</details>

