---
title: "ESM: report rates"
output: rmarkdown::html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  class.warning = "collapsable-warnings",
  message = FALSE
)
```

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
library(NpiEurope)
epi_europe <- load_epi_data()
```

We estimated daily non-reported cases for each country using the daily new 
reported cases and daily new deaths and the capture/recapture methodology
described by 
[Böhning *et al.* (2020)](https://doi.org/10.1016%2Fj.ijid.2020.06.009),
implemented in the [asymptor](https://cran.r-project.org/package=asymptor)
package.

```{r, fig.height=15}
library(asymptor)

epi_europe %>%
  group_by(Country) %>%
  mutate(NewCases = pmax(NewCases, 0),
         NewDeaths = pmax(NewDeaths, 0)) %>%
  mutate(NewCases = slider::slide_dbl(NewCases, mean, .before = 3, .after = 3),
         NewDeaths = slider::slide_dbl(NewDeaths, mean, .before = 3, .after = 3)) %>%
  summarise(estimate_asympto(Date, NewCases, NewDeaths),
            detected = NewCases) %>%
  ggplot(aes(x = date)) +
    geom_ribbon(aes(ymin = detected + lower, ymax = detected + upper)) +
    geom_line(aes(y = detected), color = "red") +
    facet_wrap(~ Country, scales = "free_y", ncol = 3)
```

```{r, child='_sessionInfo.Rmd'}
```

```{js, echo=FALSE}
(function() {
  var codes = document.querySelectorAll('.collapsable-warnings');
  var code, i, d, s, p;
  for (i = 0; i < codes.length; i++) {
    code = codes[i];
    p = code.parentNode;
    d = document.createElement('details');
    s = document.createElement('summary');
    s.innerText = 'Warnings';
    // <details><summary>Details</summary></details>
    d.appendChild(s);
    // move the code into <details>
    p.replaceChild(d, code);
    d.appendChild(code);
  }
})();
```

